name: emu2
adopt-info: emu2
summary: emu2 - A simple text-mode x86 + DOS emulator
description: |
  This is a simple DOS emulator for the Linux text console, supporting basic
  DOS system calls and console I/O.
base: core20
grade: stable
confinement: strict

apps:
  emu2:
    command: emu2
    plugs:
      - home
      - removable-media

parts:
  emu2:
    plugin: make
    source: https://github.com/dmsc/emu2.git
    build-packages:
      - gcc
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info mame | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | tr -d 'v')"
    override-build: |
      make
      cp emu2 README.md LICENSE $SNAPCRAFT_PART_INSTALL
